### ISSUE TITLE
Tulsa Lambda Lunch on October 30th (Functional Programming)

### ISSUE THREAD

**Issue by zarthross** [techlahoma/speakers-wanted#6]
**Group:** Tulsa Lambda Lunch
**Topic:** Anything Functional Programming Related.
**Date:** October 30th 11:30am ~ 12:30 pm
**Location:** 36N Tulsa
**Contact:** 
Darren Gibson
slack: zarthross or #tulsa-lambda-lunch
Email: dgibson at techlahoma dot org

**Comment by kacollins** [comment]
Ready to close this, @zarthross? Maybe create a new one for November?
